import { useState, useEffect, useRef } from "react";
import { Upload, FileAudio, ArrowLeft, Download, FileText, Sparkles, Clock, Trash2, Calendar, Mic, Square, KeyRound } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useNavigate } from "react-router-dom";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

interface SummarySection {
  heading: string;
  items: string[];
}

function parseSummary(raw: string): { overview: string; sections: SummarySection[] } {
  const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
  let overview = "";
  const sections: SummarySection[] = [];
  const headings = [
    "Executive Overview", "Main Discussion Points", "Decisions Taken",
    "Action Items", "Unresolved Questions", "Speaker Contributions"
  ];

  let currentSection: SummarySection | null = null;
  for (const line of lines) {
    if (headings.includes(line)) {
      if (line === "Executive Overview") {
        currentSection = null;
        continue;
      }
      currentSection = { heading: line, items: [] };
      sections.push(currentSection);
    } else if (!currentSection && !overview) {
      overview = line;
    } else if (!currentSection && overview) {
      overview += " " + line;
    } else if (currentSection) {
      currentSection.items.push(line.replace(/^\(|\)$/g, "").replace(/^•\s*/, ""));
    }
  }

  // Post-processing to fix action items splitting
  for (const section of sections) {
    if (section.heading === "Action Items") {
      const combined = section.items.join(" ");
      if (combined.toLowerCase().startsWith("no ") || combined.toLowerCase().includes("no action items")) {
        section.items = [combined];
      }
    }
  }

  return { overview, sections };
}

function exportAsWord(summaryText: string, title: string) {
  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8"><title>${title}</title></head>
    <body style="font-family: Calibri, Arial, sans-serif; padding: 40px;">
      <h1 style="text-align:center; color:#333;">${title}</h1>
      <hr/>
      ${summaryText.split("\n").map((line) => {
    const l = line.trim();
    if (!l) return "";
    if (["Executive Overview", "Main Discussion Points", "Decisions Taken", "Action Items", "Unresolved Questions", "Speaker Contributions"].includes(l))
      return `<h2 style="color:#059669; margin-top:18px;">${l}</h2>`;
    return `<p style="margin:4px 0;">${l}</p>`;
  }).join("")}
    </body></html>`;
  const blob = new Blob([html], { type: "application/msword" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${title.replace(/\s+/g, "_")}_summary.doc`;
  a.click();
  URL.revokeObjectURL(a.href);
}

function exportAsPdf(summaryText: string, title: string) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  const headings = ["Executive Overview", "Main Discussion Points", "Decisions Taken", "Action Items", "Unresolved Questions", "Speaker Contributions"];
  const bodyHtml = summaryText.split("\n").map((line) => {
    const l = line.trim();
    if (!l) return "";
    if (headings.includes(l)) return `<h2 style="color:#059669;margin-top:20px;font-size:18px;">${l}</h2>`;
    return `<p style="margin:4px 0;font-size:14px;line-height:1.6;">${l}</p>`;
  }).join("");

  printWindow.document.write(`
    <html><head>
      <!-- Title is explicitly empty so it doesn't print in the top right corner -->
      <title>&nbsp;</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #333; }
        h2 { border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
      </style>
    </head><body>
      <h1 style="text-align:center;">${title}</h1><hr/>
      ${bodyHtml}
      <p style="text-align:center;color:#999;font-size:12px;margin-top:40px;">Generated by Darwin • ${new Date().toLocaleDateString()}</p>
    </body></html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 300);
}

export default function CreateGame() {
  const { toast } = useToast();
  const navigate = useNavigate();
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState("Uploading file...");
  const wsRef = useRef<WebSocket | null>(null);
  const dropRef = useRef<HTMLLabelElement>(null);
  const [dragOver, setDragOver] = useState(false);

  const [calendarConnected, setCalendarConnected] = useState(false);
  const [calendarEvents, setCalendarEvents] = useState<any[]>([]);
  const [selectedEvent, setSelectedEvent] = useState<any | null>(null);

  // API Key Settings State
  const [useCustomKey, setUseCustomKey] = useState(false);
  const [customApiKey, setCustomApiKey] = useState("");
  const [selectedModel, setSelectedModel] = useState("gemini-1.5-pro");
  const [showSettings, setShowSettings] = useState(false);

  // Live Recording State
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const streamRef = useRef<MediaStream | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  const timerRef = useRef<number>();

  useEffect(() => {
    const SRC = "https://accounts.google.com/gsi/client";
    if (!document.querySelector(`script[src="${SRC}"]`)) {
      const script = document.createElement("script");
      script.src = SRC;
      script.async = true;
      script.defer = true;
      document.body.appendChild(script);
    }
  }, []);

  const connectCalendar = () => {
    if (!window.google) {
      toast({ title: "Google script loading, try again", variant: "destructive" });
      return;
    }
    const client = window.google.accounts.oauth2.initTokenClient({
      client_id: import.meta.env.VITE_GOOGLE_CLIENT_ID,
      scope: "https://www.googleapis.com/auth/calendar.readonly",
      callback: (response: any) => {
        if (response.error !== undefined) {
          toast({ title: "Calendar access denied", variant: "destructive" });
          return;
        }
        fetchCalendarEvents(response.access_token);
      },
    });
    client.requestAccessToken();
  };

  const fetchCalendarEvents = async (token: string) => {
    try {
      const timeMin = new Date();
      timeMin.setDate(timeMin.getDate() - 3); // past 3 days
      const timeMax = new Date();
      timeMax.setDate(timeMax.getDate() + 7); // next 7 days
      const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${timeMin.toISOString()}&timeMax=${timeMax.toISOString()}&singleEvents=true&orderBy=startTime`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.items) {
        setCalendarEvents(data.items);
        setCalendarConnected(true);
        toast({ title: "Calendar Connected", description: `Found ${data.items.length} recent/upcoming events.` });
      }
    } catch (e) {
      toast({ title: "Failed to fetch calendar", variant: "destructive" });
    }
  };

  const [history, setHistory] = useState<any[]>([]);
  const [activeSummary, setActiveSummary] = useState<any | null>(null);

  useEffect(() => {
    fetchHistory();
  }, []);

  async function fetchHistory() {
    try {
      const res = await fetch(`${BACKEND_URL}/api/meet-summary`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setHistory(data);
      }
    } catch (err) {
      console.error("Failed to load history", err);
    }
  }

  useEffect(() => {
    return () => {
      if (wsRef.current) wsRef.current.close();
    };
  }, []);

  async function handleUpload() {
    if (!file) { toast({ title: "Select a file first", variant: "destructive" }); return; }

    const clientId = Date.now().toString();
    const wsUrl = BACKEND_URL.replace("http", "ws") + `/ws/progress/${clientId}`;
    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;

    ws.onmessage = (event) => {
      setLoadingMsg(event.data);
    };

    const form = new FormData();
    form.append("file", file);
    if (selectedEvent) {
      const context = {
        topic: selectedEvent.summary,
        description: selectedEvent.description,
        attendees: selectedEvent.attendees?.map((a: any) => a.email || a.displayName),
      };
      form.append("calendar_context", JSON.stringify(context));
    }

    // Add custom API key and model if enabled
    if (useCustomKey && customApiKey.trim() !== "") {
      form.append("custom_api_key", customApiKey);
      form.append("model_preference", selectedModel);
    }

    form.append("client_id", clientId);

    setLoading(true);
    setLoadingMsg("Uploading file...");
    setActiveSummary(null);

    try {
      const res = await fetch(`${BACKEND_URL}/api/meet-summary`, {
        method: "POST",
        body: form,
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();

      const newSummary = {
        id: data.summary_id,
        filename: file.name,
        created_at: new Date().toISOString(),
        summary_text: data.output.summary,
        facts: data.output.facts,
        speaker_summaries: data.output.speaker_summaries
      };

      setActiveSummary(newSummary);
      setHistory(prev => [newSummary, ...prev]);
      setFile(null);
      toast({ title: "Meeting summarized ✅" });
    } catch {
      toast({ title: "Summarization failed", variant: "destructive" });
    } finally {
      if (wsRef.current) wsRef.current.close();
      setLoading(false);
    }
  }

  function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files?.[0];
    if (dropped) setFile(dropped);
  }

  async function startLiveRecording() {
    try {
      // Capture system/tab audio (browser requires getDisplayMedia)
      const stream = await navigator.mediaDevices.getDisplayMedia({
        video: true,  // required by browser API
        audio: true
      });

      // Check if audio track was actually shared
      const audioTracks = stream.getAudioTracks();
      if (audioTracks.length === 0) {
        toast({ title: "No audio track", description: "Please check 'Share tab audio' in the sharing dialog.", variant: "destructive" });
        stream.getTracks().forEach(t => t.stop());
        return;
      }

      // Immediately discard the video track — we only want audio
      stream.getVideoTracks().forEach(track => track.stop());

      // Create a new stream with only audio tracks
      const audioOnlyStream = new MediaStream(audioTracks);
      streamRef.current = stream;

      const recorder = new MediaRecorder(audioOnlyStream, { mimeType: 'audio/webm' });
      mediaRecorderRef.current = recorder;
      audioChunksRef.current = [];

      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) {
          audioChunksRef.current.push(e.data);
        }
      };

      recorder.start(1000); // Collect data every 1s
      setIsRecording(true);
      setRecordingTime(0);
      setActiveSummary(null);

      // Start a timer to show elapsed time
      timerRef.current = window.setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);

      toast({ title: "Recording started", description: "Capturing system audio. Click Stop when done." });

    } catch (err) {
      console.error(err);
      toast({ title: "Failed to start recording", description: "Ensure you grant audio permissions and check 'Share tab audio'.", variant: "destructive" });
    }
  }

  async function stopLiveRecording() {
    // Stop timer
    if (timerRef.current) clearInterval(timerRef.current);
    setIsRecording(false);

    // Stop recorder
    const recorder = mediaRecorderRef.current;
    if (!recorder || recorder.state === "inactive") {
      toast({ title: "No recording to process", variant: "destructive" });
      return;
    }

    // Wait for final data
    await new Promise<void>(resolve => {
      recorder.onstop = () => resolve();
      recorder.stop();
    });

    // Stop all tracks
    streamRef.current?.getTracks().forEach(track => track.stop());

    const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
    if (audioBlob.size < 1000) {
      toast({ title: "Recording too short or no audio captured", variant: "destructive" });
      return;
    }

    // Upload the recorded blob to the existing file upload endpoint
    const clientId = Date.now().toString();
    const wsUrl = BACKEND_URL.replace("http", "ws") + `/ws/progress/${clientId}`;
    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;
    ws.onmessage = (event) => setLoadingMsg(event.data);

    setLoading(true);
    setLoadingMsg("Uploading recorded audio...");

    try {
      const form = new FormData();
      form.append("file", audioBlob, "live_recording.webm");
      form.append("client_id", clientId);

      // Add custom API key and model if enabled
      if (useCustomKey && customApiKey.trim() !== "") {
        form.append("custom_api_key", customApiKey);
        form.append("model_preference", selectedModel);
      }

      if (selectedEvent) {
        const context = {
          topic: selectedEvent.summary,
          description: selectedEvent.description,
          attendees: selectedEvent.attendees?.map((a: any) => a.email || a.displayName),
        };
        form.append("calendar_context", JSON.stringify(context));
      }

      const res = await fetch(`${BACKEND_URL}/api/meet-summary`, {
        method: "POST",
        credentials: "include",
        body: form
      });
      if (!res.ok) throw new Error("Failed to process recording");

      await fetchHistory();
      toast({ title: "Live recording summarized ✅" });
    } catch (err) {
      toast({ title: "Processing failed", variant: "destructive" });
    } finally {
      if (wsRef.current) wsRef.current.close();
      setLoading(false);
    }
  }

  const parsed = activeSummary?.summary_text ? parseSummary(activeSummary.summary_text) : null;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between sticky top-0 z-30 shrink-0">
        <button onClick={() => navigate("/")} className="flex items-center gap-2 text-gray-500 hover:text-gray-900 text-sm font-medium transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </button>
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 relative">
            <img alt="Darwin Logo" src="/t.png" style={{ height: '100%', width: '100%', objectFit: 'contain' }} />
          </div>
          <span className="font-bold text-sm">User Dashboard</span>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar History */}
        <div className="w-80 bg-white border-r border-gray-200 flex flex-col shrink-0 overflow-hidden">
          <div className="p-4 border-b border-gray-100 flex items-center justify-between">
            <h2 className="font-semibold text-gray-800 flex items-center gap-2">
              <Clock className="w-4 h-4 text-emerald-600" /> Past Meetings
            </h2>
          </div>
          <div className="flex-1 overflow-y-auto p-3 space-y-2">
            <button
              onClick={() => { setActiveSummary(null); setFile(null); }}
              className={`w-full text-left px-4 py-3 rounded-xl border transition-all flex items-center gap-3 shadow-sm ${!activeSummary && !loading ? "bg-emerald-600 text-white border-emerald-600 hover:bg-emerald-700" : "bg-emerald-50 text-emerald-800 border-emerald-200 hover:bg-emerald-100"
                }`}
            >
              <Upload className="w-4 h-4 shrink-0" />
              <span className="text-sm font-semibold">New Summarization</span>
            </button>

            <div className="my-2 border-t border-gray-100" />

            {history.length === 0 ? (
              <p className="text-xs text-gray-400 text-center py-6">No previous summaries found.</p>
            ) : (
              history.map((item) => (
                <button
                  key={item.id}
                  onClick={() => setActiveSummary(item)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg border transition-all group ${activeSummary?.id === item.id
                      ? "bg-white border-emerald-300 shadow-sm ring-1 ring-emerald-500/20"
                      : "bg-white border-gray-100 hover:border-gray-300 hover:bg-gray-50 text-gray-600"
                    }`}
                >
                  <p className={`text-sm font-medium truncate mb-1 ${activeSummary?.id === item.id ? "text-emerald-700" : "text-gray-800"}`}>
                    {item.filename}
                  </p>
                  <p className="text-xs text-gray-400">
                    {new Date(item.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                </button>
              ))
            )}
          </div>

          {/* Settings Toggle at Bottom of Sidebar */}
          <div className="p-4 border-t border-gray-100 bg-gray-50/50">
            <button
              onClick={() => setShowSettings(!showSettings)}
              className={`w-full text-left px-3 py-2.5 rounded-lg border transition-all flex items-center justify-between shadow-sm ${showSettings
                  ? "bg-slate-800 text-white border-slate-700"
                  : "bg-white text-gray-700 border-gray-200 hover:bg-gray-50"
                }`}
            >
              <span className="flex items-center gap-2 text-sm font-medium">
                <KeyRound className="w-4 h-4" />
                API Configuration
              </span>
            </button>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 overflow-y-auto p-6 md:p-10 w-full relative">
          <div className="max-w-4xl mx-auto w-full">

            {/* Upload Area */}
            {!activeSummary && !loading && !isRecording && (
              <div className="mt-10">
                <h1 className="text-3xl font-bold text-center mb-2">Meeting Summarizer</h1>
                <p className="text-gray-500 text-center mb-10 text-sm">Upload your meeting recording and let AI do the rest.</p>
                <div className="space-y-4 max-w-2xl mx-auto">
                  <label
                    ref={dropRef}
                    onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                    onDragLeave={() => setDragOver(false)}
                    onDrop={handleDrop}
                    className={`flex flex-col items-center justify-center border-2 border-dashed rounded-2xl p-10 cursor-pointer transition-all duration-200 ${dragOver ? "border-emerald-500 bg-emerald-50" : file ? "border-emerald-300 bg-emerald-50/50" : "border-gray-300 bg-white hover:border-emerald-400 hover:bg-emerald-50/30"
                      }`}
                  >
                    <FileAudio className={`w-10 h-10 mb-3 ${file ? "text-emerald-600" : "text-gray-400"}`} />
                    <span className="text-sm text-gray-600 mb-1">{file ? file.name : "Drag & drop an audio/video file, or click to browse"}</span>
                    {file && <span className="text-xs text-gray-400">{(file.size / 1024 / 1024).toFixed(1)} MB</span>}
                    <input type="file" className="hidden" accept="audio/*,video/*" onChange={(e) => setFile(e.target.files?.[0] || null)} />
                  </label>

                  <div className="w-full">
                    {!calendarConnected ? (
                      <button type="button" onClick={connectCalendar} className="text-sm bg-white border px-4 py-2 rounded-xl border-gray-200 outline-none flex items-center gap-2 hover:bg-gray-50 text-gray-700 w-full justify-center transition-colors shadow-sm">
                        <Calendar className="w-4 h-4 text-emerald-600" /> Auto-fill meeting details using Google Calendar
                      </button>
                    ) : (
                      <select className="w-full p-3 border border-emerald-300 bg-emerald-50 rounded-xl text-sm outline-none text-emerald-900 shadow-sm" onChange={(e) => setSelectedEvent(calendarEvents.find(ev => ev.id === e.target.value))}>
                        <option value="">-- No specific meeting context --</option>
                        {calendarEvents.map(ev => (
                          <option key={ev.id} value={ev.id}>📝 {ev.summary || "Untitled"} - {new Date(ev.start?.dateTime || ev.start?.date).toLocaleDateString()}</option>
                        ))}
                      </select>
                    )}
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <button
                      onClick={handleUpload}
                      disabled={!file}
                      className="w-full bg-emerald-600 text-white py-3 rounded-xl font-semibold flex items-center justify-center gap-2 hover:bg-emerald-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-emerald-200"
                    >
                      <Upload className="w-4 h-4" /> Upload File
                    </button>
                    <button
                      onClick={startLiveRecording}
                      className="w-full bg-red-50 text-red-600 border border-red-200 py-3 rounded-xl font-semibold flex items-center justify-center gap-2 hover:bg-red-100 transition-colors shadow-sm"
                    >
                      <Mic className="w-4 h-4" /> Record Live
                    </button>
                  </div>

                  {/* API Configuration Settings Panel */}
                  {showSettings && (
                    <div className="mt-6 bg-white border border-gray-200 rounded-2xl p-6 shadow-sm animate-fade-in relative overflow-hidden">
                      <div className="absolute top-0 left-0 w-2 h-full bg-slate-800"></div>
                      <h3 className="text-lg font-bold text-gray-800 mb-1 flex items-center gap-2">
                        <KeyRound className="w-5 h-5 text-slate-700" /> API Configuration
                      </h3>
                      <p className="text-sm text-gray-500 mb-5">
                        Choose to use our default models or provide your own API key for custom rate limits.
                      </p>

                      <div className="space-y-5">
                        <label className="flex items-center gap-3 cursor-pointer group">
                          <div className="relative flex items-center">
                            <input
                              type="checkbox"
                              checked={useCustomKey}
                              onChange={(e) => setUseCustomKey(e.target.checked)}
                              className="peer sr-only"
                            />
                            <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-slate-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-slate-800"></div>
                          </div>
                          <span className="text-sm font-medium text-gray-700 group-hover:text-gray-900 transition-colors">
                            I have my own API key
                          </span>
                        </label>

                        <div className={`space-y-4 transition-all duration-300 origin-top overflow-hidden ${useCustomKey ? 'max-h-[500px] opacity-100 mt-4' : 'max-h-0 opacity-0 m-0'}`}>
                          <div>
                            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 list-none">
                              Select Model
                            </label>
                            <select
                              value={selectedModel}
                              onChange={(e) => setSelectedModel(e.target.value)}
                              className="w-full p-2.5 border border-gray-200 bg-gray-50 rounded-xl text-sm outline-none text-gray-800 focus:border-slate-500 focus:ring-1 focus:ring-slate-500 transition-all font-medium"
                            >
                              <option value="gemini-1.5-pro">Gemini 1.5 Pro (Recommended)</option>
                              <option value="gemini-1.5-flash">Gemini 1.5 Flash (Faster)</option>
                              <option value="gemini-1.0-pro">Gemini 1.0 Pro</option>
                            </select>
                          </div>

                          <div>
                            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 flex justify-between">
                              API Key
                            </label>
                            <input
                              type="password"
                              value={customApiKey}
                              onChange={(e) => setCustomApiKey(e.target.value)}
                              placeholder="Enter your API Key (e.g. AIzaSy...)"
                              className="w-full p-2.5 border border-gray-200 bg-white rounded-xl text-sm outline-none text-gray-800 focus:border-slate-500 focus:ring-1 focus:ring-slate-500 transition-all"
                            />
                            {customApiKey && customApiKey.length < 20 && (
                              <p className="text-xs text-amber-600 mt-1.5 flex items-center gap-1">
                                ⚠ This API key looks too short to be valid.
                              </p>
                            )}
                          </div>

                          <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 flex items-start gap-2">
                            <span className="text-slate-500 mt-0.5">ℹ️</span>
                            <p className="text-[11px] text-slate-600 leading-relaxed">
                              Your API key is only used during the current session and sent securely to the server. It is <strong>not</strong> stored permanently in our database.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Live Recording Area */}
            {isRecording && (
              <div className="mt-10 max-w-2xl mx-auto animate-fade-in">
                <div className="bg-white border-2 border-red-200 rounded-2xl p-8 shadow-sm">
                  <div className="flex items-center justify-between mb-6 border-b border-gray-100 pb-4">
                    <div className="flex items-center gap-3">
                      <span className="relative flex h-3 w-3">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-3 w-3 bg-red-500"></span>
                      </span>
                      <h2 className="text-lg font-bold text-gray-800">Recording System Audio</h2>
                    </div>
                    <button onClick={stopLiveRecording} className="bg-red-600 text-white px-4 py-2 rounded-lg text-sm font-semibold flex items-center gap-2 hover:bg-red-700 transition-colors shadow-md shadow-red-200">
                      <Square className="w-4 h-4" /> Stop & Summarize
                    </button>
                  </div>
                  <div className="bg-gray-50 rounded-xl p-8 flex flex-col items-center justify-center min-h-[200px] border border-gray-100 shadow-inner">
                    <p className="text-5xl font-mono font-bold text-gray-800 mb-4 tabular-nums">
                      {String(Math.floor(recordingTime / 60)).padStart(2, '0')}:{String(recordingTime % 60).padStart(2, '0')}
                    </p>
                    <div className="flex items-center gap-1 mb-4">
                      {[...Array(12)].map((_, i) => (
                        <div key={i} className="w-1.5 bg-red-400 rounded-full animate-pulse" style={{ height: `${12 + Math.random() * 24}px`, animationDelay: `${i * 0.1}s` }} />
                      ))}
                    </div>
                    <p className="text-sm text-gray-500">Capturing audio from the shared tab. Click <b>Stop & Summarize</b> when done.</p>
                  </div>
                </div>
              </div>
            )}

            {/* Loading */}
            {loading && (
              <div className="flex flex-col items-center justify-center py-32">
                <div className="relative w-16 h-16 mb-8">
                  <div className="absolute inset-0 rounded-full border-4 border-gray-200" />
                  <div className="absolute inset-0 rounded-full border-4 border-emerald-500 border-t-transparent animate-spin" />
                  <div className="absolute inset-2 rounded-full border-4 border-emerald-300 border-b-transparent animate-spin" style={{ animationDirection: "reverse", animationDuration: "1.5s" }} />
                </div>
                <p key={loadingMsg} className="text-gray-600 font-medium text-sm animate-fade-in">{loadingMsg}</p>
                <p className="text-gray-400 text-xs mt-2">This may take a few minutes depending on the file size.</p>
              </div>
            )}

            {/* View Summary */}
            {activeSummary && parsed && (
              <div className="space-y-6 pb-20 animate-fade-in">
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-gray-200 pb-6">
                  <div>
                    <h1 className="text-2xl font-bold text-gray-900 break-all">{activeSummary.filename}</h1>
                    <p className="text-sm text-gray-500 mt-1 flex items-center gap-1.5">
                      <Clock className="w-3.5 h-3.5" /> Generated on {new Date(activeSummary.created_at).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => exportAsPdf(activeSummary.summary_text, activeSummary.filename)} className="flex items-center gap-1.5 bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:border-emerald-300 hover:text-emerald-700 transition-all shadow-sm">
                      <Download className="w-3.5 h-3.5" /> Save PDF
                    </button>
                    <button onClick={() => exportAsWord(activeSummary.summary_text, activeSummary.filename)} className="flex items-center gap-1.5 bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:border-emerald-300 hover:text-emerald-700 transition-all shadow-sm">
                      <FileText className="w-3.5 h-3.5" /> Save docx
                    </button>
                  </div>
                </div>

                <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
                  <div className="p-6 md:p-8 border-b border-gray-100 bg-emerald-50/40">
                    <h2 className="text-sm font-semibold uppercase tracking-wide text-emerald-600 mb-2">Executive Overview</h2>
                    <p className="text-gray-800 leading-relaxed font-medium text-lg">{parsed.overview || "No overview available."}</p>
                  </div>
                  <div className="divide-y divide-gray-100">
                    {parsed.sections.map((section, i) => (
                      <div key={i} className="p-6 md:p-8">
                        <h3 className="text-sm font-bold uppercase tracking-wide text-gray-500 mb-4">{section.heading}</h3>
                        {section.items.length > 0 ? (
                          <ul className="space-y-3">
                            {section.items.map((item, j) => (
                              <li key={j} className="flex items-start gap-3 text-base text-gray-700 leading-relaxed">
                                <span className="text-emerald-500 mt-1 shrink-0 bg-emerald-100 w-1.5 h-1.5 rounded-full" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        ) : (<p className="text-sm text-gray-400 italic">None identified.</p>)}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Facts / Tags */}
                {activeSummary.facts && (
                  <div className="bg-white border border-gray-200 rounded-2xl p-6 md:p-8 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wide text-gray-500 mb-4">Extracted Intel</h3>
                    <div className="grid md:grid-cols-2 gap-6">
                      {activeSummary.facts.topics?.length > 0 && (
                        <div>
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Topics Covered</p>
                          <div className="flex flex-wrap gap-2">
                            {activeSummary.facts.topics.map((t: string, i: number) => (
                              <span key={i} className="bg-emerald-50 text-emerald-700 text-sm px-3 py-1.5 rounded-xl font-medium border border-emerald-100">{t}</span>
                            ))}
                          </div>
                        </div>
                      )}
                      {activeSummary.facts.participants?.length > 0 && (
                        <div>
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Participants Identified</p>
                          <div className="flex flex-wrap gap-2">
                            {activeSummary.facts.participants.map((p: string, i: number) => (
                              <span key={i} className="bg-blue-50 text-blue-700 text-sm px-3 py-1.5 rounded-xl font-medium border border-blue-100">{p}</span>
                            ))}
                          </div>
                        </div>
                      )}

                      {activeSummary.facts.action_items?.length > 0 && (
                        <div className="md:col-span-2 mt-2 pt-4 border-t border-gray-100">
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">Assigned Action Items</p>
                          <div className="space-y-3">
                            {activeSummary.facts.action_items.map((task: any, i: number) => {
                              const strDesc = String(task.task || "");
                              const strAssgn = String(task.assignee || "");
                              const hasEmail = strDesc.includes('@') || strAssgn.includes('@');
                              return (
                                <div key={i} className="bg-gray-50 border border-gray-100 rounded-xl p-4 flex items-start justify-between gap-4">
                                  <div className="flex-1">
                                    <p className="text-sm font-medium text-gray-900">{task.task}</p>
                                    <p className="text-xs text-gray-500 mt-1">Assignee: {task.assignee || "Unassigned"} {task.deadline && task.deadline !== "null" ? `• Due: ${task.deadline}` : ""}</p>
                                  </div>
                                  <div className="shrink-0 pt-1">
                                    {hasEmail ? (
                                      <span className="bg-emerald-100 text-emerald-700 text-[10px] uppercase font-bold tracking-wide px-2 py-1 rounded-md">Email Sent</span>
                                    ) : (
                                      <span className="bg-yellow-100 text-yellow-700 text-[10px] uppercase font-bold tracking-wide px-2 py-1 rounded-md mb-1 block text-center">Pending Email</span>
                                    )}
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
}
