import { useState, useEffect, useRef } from "react";
import { Upload, FileAudio, ArrowLeft, Download, FileText, Sparkles, Clock, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useNavigate } from "react-router-dom";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

const STATUS_MESSAGES = [
  "Uploading file…",
  "Transcribing audio…",
  "Identifying speakers…",
  "Extracting key insights…",
  "Generating summary…",
  "Almost there…",
];

interface SummarySection {
  heading: string;
  items: string[];
}

function parseSummary(raw: string): { overview: string; sections: SummarySection[] } {
  const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
  let overview = "";
  const sections: SummarySection[] = [];
  const headings = [
    "Executive Overview", "Main Discussion Points", "Decisions Taken",
    "Action Items", "Unresolved Questions", "Speaker Contributions"
  ];

  let currentSection: SummarySection | null = null;
  for (const line of lines) {
    if (headings.includes(line)) {
      if (line === "Executive Overview") {
        currentSection = null;
        continue;
      }
      currentSection = { heading: line, items: [] };
      sections.push(currentSection);
    } else if (!currentSection && !overview) {
      overview = line;
    } else if (!currentSection && overview) {
      overview += " " + line;
    } else if (currentSection) {
      currentSection.items.push(line.replace(/^\(|\)$/g, "").replace(/^•\s*/, ""));
    }
  }

  // Post-processing to fix action items splitting
  for (const section of sections) {
    if (section.heading === "Action Items") {
      const combined = section.items.join(" ");
      if (combined.toLowerCase().startsWith("no ") || combined.toLowerCase().includes("no action items")) {
        section.items = [combined];
      }
    }
  }

  return { overview, sections };
}

function exportAsWord(summaryText: string, title: string) {
  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8"><title>${title}</title></head>
    <body style="font-family: Calibri, Arial, sans-serif; padding: 40px;">
      <h1 style="text-align:center; color:#333;">${title}</h1>
      <hr/>
      ${summaryText.split("\n").map((line) => {
          const l = line.trim();
          if (!l) return "";
          if (["Executive Overview", "Main Discussion Points", "Decisions Taken", "Action Items", "Unresolved Questions", "Speaker Contributions"].includes(l))
            return `<h2 style="color:#059669; margin-top:18px;">${l}</h2>`;
          return `<p style="margin:4px 0;">${l}</p>`;
        }).join("")}
    </body></html>`;
  const blob = new Blob([html], { type: "application/msword" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${title.replace(/\s+/g, "_")}_summary.doc`;
  a.click();
  URL.revokeObjectURL(a.href);
}

function exportAsPdf(summaryText: string, title: string) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  const headings = ["Executive Overview", "Main Discussion Points", "Decisions Taken", "Action Items", "Unresolved Questions", "Speaker Contributions"];
  const bodyHtml = summaryText.split("\n").map((line) => {
      const l = line.trim();
      if (!l) return "";
      if (headings.includes(l)) return `<h2 style="color:#059669;margin-top:20px;font-size:18px;">${l}</h2>`;
      return `<p style="margin:4px 0;font-size:14px;line-height:1.6;">${l}</p>`;
    }).join("");

  printWindow.document.write(`
    <html><head>
      <!-- Title is explicitly empty so it doesn't print in the top right corner -->
      <title>&nbsp;</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #333; }
        h2 { border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
      </style>
    </head><body>
      <h1 style="text-align:center;">${title}</h1><hr/>
      ${bodyHtml}
      <p style="text-align:center;color:#999;font-size:12px;margin-top:40px;">Generated by Darwin • ${new Date().toLocaleDateString()}</p>
    </body></html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 300);
}

export default function CreateGame() {
  const { toast } = useToast();
  const navigate = useNavigate();
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [statusIndex, setStatusIndex] = useState(0);
  const intervalRef = useRef<number>();
  const dropRef = useRef<HTMLLabelElement>(null);
  const [dragOver, setDragOver] = useState(false);

  const [history, setHistory] = useState<any[]>([]);
  const [activeSummary, setActiveSummary] = useState<any | null>(null);

  useEffect(() => {
    fetchHistory();
  }, []);

  async function fetchHistory() {
    try {
      const res = await fetch(`${BACKEND_URL}/api/meet-summary`, { credentials: "include" });
      if (res.ok) {
        const data = await res.json();
        setHistory(data);
      }
    } catch (err) {
      console.error("Failed to load history", err);
    }
  }

  useEffect(() => {
    if (loading) {
      setStatusIndex(0);
      intervalRef.current = window.setInterval(() => {
        setStatusIndex((prev) => (prev + 1) % STATUS_MESSAGES.length);
      }, 3500);
    } else {
      if (intervalRef.current) clearInterval(intervalRef.current);
    }
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, [loading]);

  async function handleUpload() {
    if (!file) { toast({ title: "Select a file first", variant: "destructive" }); return; }
    const form = new FormData();
    form.append("file", file);
    setLoading(true);
    setActiveSummary(null);

    try {
      const res = await fetch(`${BACKEND_URL}/api/meet-summary`, {
        method: "POST",
        body: form,
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      
      const newSummary = {
        id: data.summary_id,
        filename: file.name,
        created_at: new Date().toISOString(),
        summary_text: data.output.summary,
        facts: data.output.facts,
        speaker_summaries: data.output.speaker_summaries
      };
      
      setActiveSummary(newSummary);
      setHistory(prev => [newSummary, ...prev]);
      setFile(null);
      toast({ title: "Meeting summarized ✅" });
    } catch {
      toast({ title: "Summarization failed", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  }

  function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files?.[0];
    if (dropped) setFile(dropped);
  }

  const parsed = activeSummary?.summary_text ? parseSummary(activeSummary.summary_text) : null;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between sticky top-0 z-30 shrink-0">
        <button onClick={() => navigate("/")} className="flex items-center gap-2 text-gray-500 hover:text-gray-900 text-sm font-medium transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </button>
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 relative">
            <img alt="Darwin Logo" src="/t.png" style={{ height: '100%', width: '100%', objectFit: 'contain' }} />
          </div>
          <span className="font-bold text-sm">User Dashboard</span>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar History */}
        <div className="w-80 bg-white border-r border-gray-200 flex flex-col shrink-0 overflow-hidden">
          <div className="p-4 border-b border-gray-100 flex items-center justify-between">
            <h2 className="font-semibold text-gray-800 flex items-center gap-2">
              <Clock className="w-4 h-4 text-emerald-600" /> Past Meetings
            </h2>
          </div>
          <div className="flex-1 overflow-y-auto p-3 space-y-2">
            <button
              onClick={() => { setActiveSummary(null); setFile(null); }}
              className={`w-full text-left px-4 py-3 rounded-xl border transition-all flex items-center gap-3 shadow-sm ${
                !activeSummary && !loading ? "bg-emerald-600 text-white border-emerald-600 hover:bg-emerald-700" : "bg-emerald-50 text-emerald-800 border-emerald-200 hover:bg-emerald-100"
              }`}
            >
              <Upload className="w-4 h-4 shrink-0" />
              <span className="text-sm font-semibold">New Summarization</span>
            </button>

            <div className="my-2 border-t border-gray-100" />

            {history.length === 0 ? (
              <p className="text-xs text-gray-400 text-center py-6">No previous summaries found.</p>
            ) : (
              history.map((item) => (
                <button
                  key={item.id}
                  onClick={() => setActiveSummary(item)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg border transition-all group ${
                    activeSummary?.id === item.id 
                      ? "bg-white border-emerald-300 shadow-sm ring-1 ring-emerald-500/20" 
                      : "bg-white border-gray-100 hover:border-gray-300 hover:bg-gray-50 text-gray-600"
                  }`}
                >
                  <p className={`text-sm font-medium truncate mb-1 ${activeSummary?.id === item.id ? "text-emerald-700" : "text-gray-800"}`}>
                    {item.filename}
                  </p>
                  <p className="text-xs text-gray-400">
                    {new Date(item.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                </button>
              ))
            )}
          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 overflow-y-auto p-6 md:p-10 w-full relative">
          <div className="max-w-4xl mx-auto w-full">
            
            {/* Upload Area */}
            {!activeSummary && !loading && (
              <div className="mt-10">
                <h1 className="text-3xl font-bold text-center mb-2">Meeting Summarizer</h1>
                <p className="text-gray-500 text-center mb-10 text-sm">Upload your meeting recording and let AI do the rest.</p>
                <div className="space-y-4 max-w-2xl mx-auto">
                  <label
                    ref={dropRef}
                    onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                    onDragLeave={() => setDragOver(false)}
                    onDrop={handleDrop}
                    className={`flex flex-col items-center justify-center border-2 border-dashed rounded-2xl p-10 cursor-pointer transition-all duration-200 ${
                      dragOver ? "border-emerald-500 bg-emerald-50" : file ? "border-emerald-300 bg-emerald-50/50" : "border-gray-300 bg-white hover:border-emerald-400 hover:bg-emerald-50/30"
                    }`}
                  >
                    <FileAudio className={`w-10 h-10 mb-3 ${file ? "text-emerald-600" : "text-gray-400"}`} />
                    <span className="text-sm text-gray-600 mb-1">{file ? file.name : "Drag & drop an audio/video file, or click to browse"}</span>
                    {file && <span className="text-xs text-gray-400">{(file.size / 1024 / 1024).toFixed(1)} MB</span>}
                    <input type="file" className="hidden" accept="audio/*,video/*" onChange={(e) => setFile(e.target.files?.[0] || null)} />
                  </label>
                  <button
                    onClick={handleUpload}
                    disabled={!file}
                    className="w-full bg-emerald-600 text-white py-3 rounded-xl font-semibold flex items-center justify-center gap-2 hover:bg-emerald-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-emerald-200"
                  >
                    <Upload className="w-4 h-4" /> Upload & Summarize
                  </button>
                </div>
              </div>
            )}

            {/* Loading */}
            {loading && (
              <div className="flex flex-col items-center justify-center py-32">
                <div className="relative w-16 h-16 mb-8">
                  <div className="absolute inset-0 rounded-full border-4 border-gray-200" />
                  <div className="absolute inset-0 rounded-full border-4 border-emerald-500 border-t-transparent animate-spin" />
                  <div className="absolute inset-2 rounded-full border-4 border-emerald-300 border-b-transparent animate-spin" style={{ animationDirection: "reverse", animationDuration: "1.5s" }} />
                </div>
                <p key={statusIndex} className="text-gray-600 font-medium text-sm animate-fade-in">{STATUS_MESSAGES[statusIndex]}</p>
                <p className="text-gray-400 text-xs mt-2">This may take a few minutes depending on the file size.</p>
              </div>
            )}

            {/* View Summary */}
            {activeSummary && parsed && (
              <div className="space-y-6 pb-20 animate-fade-in">
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-gray-200 pb-6">
                  <div>
                    <h1 className="text-2xl font-bold text-gray-900 break-all">{activeSummary.filename}</h1>
                    <p className="text-sm text-gray-500 mt-1 flex items-center gap-1.5">
                      <Clock className="w-3.5 h-3.5" /> Generated on {new Date(activeSummary.created_at).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => exportAsPdf(activeSummary.summary_text, activeSummary.filename)} className="flex items-center gap-1.5 bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:border-emerald-300 hover:text-emerald-700 transition-all shadow-sm">
                      <Download className="w-3.5 h-3.5" /> Save PDF
                    </button>
                    <button onClick={() => exportAsWord(activeSummary.summary_text, activeSummary.filename)} className="flex items-center gap-1.5 bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:border-emerald-300 hover:text-emerald-700 transition-all shadow-sm">
                      <FileText className="w-3.5 h-3.5" /> Save docx
                    </button>
                  </div>
                </div>

                <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
                  <div className="p-6 md:p-8 border-b border-gray-100 bg-emerald-50/40">
                    <h2 className="text-sm font-semibold uppercase tracking-wide text-emerald-600 mb-2">Executive Overview</h2>
                    <p className="text-gray-800 leading-relaxed font-medium text-lg">{parsed.overview || "No overview available."}</p>
                  </div>
                  <div className="divide-y divide-gray-100">
                    {parsed.sections.map((section, i) => (
                      <div key={i} className="p-6 md:p-8">
                        <h3 className="text-sm font-bold uppercase tracking-wide text-gray-500 mb-4">{section.heading}</h3>
                        {section.items.length > 0 ? (
                          <ul className="space-y-3">
                            {section.items.map((item, j) => (
                              <li key={j} className="flex items-start gap-3 text-base text-gray-700 leading-relaxed">
                                <span className="text-emerald-500 mt-1 shrink-0 bg-emerald-100 w-1.5 h-1.5 rounded-full" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        ) : (<p className="text-sm text-gray-400 italic">None identified.</p>)}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Facts / Tags */}
                {activeSummary.facts && (
                  <div className="bg-white border border-gray-200 rounded-2xl p-6 md:p-8 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wide text-gray-500 mb-4">Extracted Intel</h3>
                    <div className="grid md:grid-cols-2 gap-6">
                      {activeSummary.facts.topics?.length > 0 && (
                        <div>
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Topics Covered</p>
                          <div className="flex flex-wrap gap-2">
                            {activeSummary.facts.topics.map((t: string, i: number) => (
                              <span key={i} className="bg-emerald-50 text-emerald-700 text-sm px-3 py-1.5 rounded-xl font-medium border border-emerald-100">{t}</span>
                            ))}
                          </div>
                        </div>
                      )}
                      {activeSummary.facts.participants?.length > 0 && (
                        <div>
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Participants Identified</p>
                          <div className="flex flex-wrap gap-2">
                            {activeSummary.facts.participants.map((p: string, i: number) => (
                              <span key={i} className="bg-blue-50 text-blue-700 text-sm px-3 py-1.5 rounded-xl font-medium border border-blue-100">{p}</span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}
            
          </div>
        </div>
      </div>
    </div>
  );
}
